### PR TITLE
Feature/sidebar

### PR DESCRIPTION
**Pull request by rekloyd**

### CODE REVIEW

**Comment by JiajunQiuWu** [comment]
me parece bien

**Comment by rekloyd** [comment]
Hi guys! I've created this pull request with our latest version of the code. Enjoy :)

**Review by JiajunQiuWu — APPROVED** [review]
okey

**Review by Jaranag — APPROVED** [review]
Still have to work on styles.
Good start to the project, we finish today.

**Review by JoseAlfredoMiguel — APPROVED** [review]
Hola

**Pull request closed without merging**
